# Generated by Django 3.1.7 on 2021-03-07 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.FileField(upload_to='films')),
            ],
        ),
        migrations.CreateModel(
            name='Tamrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ersal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('nomre', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('Tamrin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ersalha', to='main.tamrin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ersalha', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
